### ISSUE TITLE
Class android.support.v7.widget.AppCompatCheckedTextView conflict

### ISSUE THREAD

**Issue by aecz** [Appverse/Nativescript-NG2-Showcase#3]
If you see this kind of issue:

`Exception in thread "main" java.lang.IllegalArgumentException: Class android.sup
port.v7.widget.AppCompatCheckedTextView conflict: E:\Native Script\Ref-App\platf
orms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\2
3.4.0\jars\classes.jar and E:\Native Script\Ref-App\platforms\android\build\inte
rmediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\jars\classes.jar
at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
at com.telerik.metadata.Builder.build(Builder.java:39)
at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED`

Try running, in the directory platform/android:
`gradlew clean buildapk --stacktrace --info`

**Comment by martin-mitro** [comment]
I also had similar problem: android.support.v4.app.FragmentState$1 conflict. Running ./gradlew clean from platform/android helped. Thanks.
